### ISSUE TITLE
Add a reader to show all messages

### ISSUE THREAD

**Issue by TheTechRobo** [Sanqui/discard2#4]
Would be helpful for my URL extractor so I don't have to parse through the raw-print or the raw-jsonl.

**Comment by Sanqui** [comment]
Did you try the `print` output format?  It should output messages in the format of
`[timestamp] channel: <user> message text`
which should be suitable for your extractor.  Of course, I could add a format that would output only message text, too.

**Comment by TheTechRobo** [comment]
~~That's not shown in the README, is it? I only see raw-print.~~

I'm blind.

**Comment by TheTechRobo** [comment]
Sorry for wasting your time. Somehow I missed that output format.
