### ISSUE TITLE
Create "result" structure for tasks

### ISSUE THREAD

**Issue by Sanqui** [Sanqui/discard2#6]
Individual tasks should report on their runtime results: in particular, names of servers and channels, IDs of first and last messages encountered, perhaps total number of messages seen.

Logical way of implementing #3 as well as paving way for incremental jobs ("get all messages up to the newest messages in this finished job").

**Comment by TheTechRobo** [comment]
Also might be nice to add an "explain" task that just shows whatever is put in as the result structure.

**Comment by Sanqui** [comment]
Implemented in acfb0db0033f5f2a6f6985698f955e32e3fcaf91, although can be improved ofc.
